// Copyright 2026 The ninsun-labs Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: resolver/v1/resolver.proto

// Package ugallu.resolver.v1 is the gRPC contract for ugallu-resolver.
// The service is exposed on a Unix socket (per-node, fast path) and
// on a ClusterIP Service (cluster-wide). Clients are detection
// sources, reasoners, and responders that need to map low-level
// identifiers (cgroup ID, PID, IP, container ID, SA username) into a
// SubjectTier1 snapshot suitable for embedding in a SecurityEvent.

package resolverv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Resolver_ResolveByCgroupID_FullMethodName    = "/ugallu.resolver.v1.Resolver/ResolveByCgroupID"
	Resolver_ResolveByPID_FullMethodName         = "/ugallu.resolver.v1.Resolver/ResolveByPID"
	Resolver_ResolveByPodIP_FullMethodName       = "/ugallu.resolver.v1.Resolver/ResolveByPodIP"
	Resolver_ResolveByPodUID_FullMethodName      = "/ugallu.resolver.v1.Resolver/ResolveByPodUID"
	Resolver_ResolveByContainerID_FullMethodName = "/ugallu.resolver.v1.Resolver/ResolveByContainerID"
	Resolver_ResolveBySAUsername_FullMethodName  = "/ugallu.resolver.v1.Resolver/ResolveBySAUsername"
	Resolver_Watch_FullMethodName                = "/ugallu.resolver.v1.Resolver/Watch"
)

// ResolverClient is the client API for Resolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Resolver is the subject lookup service exposed by ugallu-resolver.
//
// Endpoints (deployed by the umbrella chart):
//   - Unix socket:    /var/run/ugallu/resolver.sock          (local-node)
//   - ClusterIP svc:  ugallu-resolver.ugallu-system-privileged.svc:443 (cluster-wide)
//
// All RPCs are best-effort. On lookup failure the response is returned
// with the appropriate failure marker (partial / tombstone / unresolved)
// so callers can emit a degraded SecurityEvent rather than block.
type ResolverClient interface {
	// ResolveByCgroupID maps a kernel cgroup ID (typically from a Tetragon or
	// own eBPF event) to a Subject.
	ResolveByCgroupID(ctx context.Context, in *CgroupIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error)
	// ResolveByPID maps a host PID to a Subject. Uses /proc + cgroup index.
	ResolveByPID(ctx context.Context, in *PIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error)
	// ResolveByPodIP maps a Pod IP (IPv4 or IPv6) to a Subject.
	ResolveByPodIP(ctx context.Context, in *PodIPRequest, opts ...grpc.CallOption) (*SubjectResponse, error)
	// ResolveByPodUID maps a Pod UID (e.g. from an audit log entry) to a Subject.
	ResolveByPodUID(ctx context.Context, in *PodUIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error)
	// ResolveByContainerID maps a CRI container ID (e.g. "containerd://abc...")
	// to a Subject.
	ResolveByContainerID(ctx context.Context, in *ContainerIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error)
	// ResolveBySAUsername maps a Kubernetes auth username
	// (e.g. "system:serviceaccount:default:foo") to a Subject. Intelligent
	// parsing: system:serviceaccount:<ns>:<name>, system:node:<hostname>,
	// other system:* (returns SystemUser external), or non-system (ExternalUser).
	ResolveBySAUsername(ctx context.Context, in *SAUsernameRequest, opts ...grpc.CallOption) (*SubjectResponse, error)
	// Watch streams SubjectChange events for the given filter. Server-streaming.
	// Planned for v1beta1 (operator hot-reload + cache prefetch).
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubjectChange], error)
}

type resolverClient struct {
	cc grpc.ClientConnInterface
}

func NewResolverClient(cc grpc.ClientConnInterface) ResolverClient {
	return &resolverClient{cc}
}

func (c *resolverClient) ResolveByCgroupID(ctx context.Context, in *CgroupIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectResponse)
	err := c.cc.Invoke(ctx, Resolver_ResolveByCgroupID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) ResolveByPID(ctx context.Context, in *PIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectResponse)
	err := c.cc.Invoke(ctx, Resolver_ResolveByPID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) ResolveByPodIP(ctx context.Context, in *PodIPRequest, opts ...grpc.CallOption) (*SubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectResponse)
	err := c.cc.Invoke(ctx, Resolver_ResolveByPodIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) ResolveByPodUID(ctx context.Context, in *PodUIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectResponse)
	err := c.cc.Invoke(ctx, Resolver_ResolveByPodUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) ResolveByContainerID(ctx context.Context, in *ContainerIDRequest, opts ...grpc.CallOption) (*SubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectResponse)
	err := c.cc.Invoke(ctx, Resolver_ResolveByContainerID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) ResolveBySAUsername(ctx context.Context, in *SAUsernameRequest, opts ...grpc.CallOption) (*SubjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubjectResponse)
	err := c.cc.Invoke(ctx, Resolver_ResolveBySAUsername_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resolverClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubjectChange], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Resolver_ServiceDesc.Streams[0], Resolver_Watch_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, SubjectChange]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Resolver_WatchClient = grpc.ServerStreamingClient[SubjectChange]

// ResolverServer is the server API for Resolver service.
// All implementations must embed UnimplementedResolverServer
// for forward compatibility.
//
// Resolver is the subject lookup service exposed by ugallu-resolver.
//
// Endpoints (deployed by the umbrella chart):
//   - Unix socket:    /var/run/ugallu/resolver.sock          (local-node)
//   - ClusterIP svc:  ugallu-resolver.ugallu-system-privileged.svc:443 (cluster-wide)
//
// All RPCs are best-effort. On lookup failure the response is returned
// with the appropriate failure marker (partial / tombstone / unresolved)
// so callers can emit a degraded SecurityEvent rather than block.
type ResolverServer interface {
	// ResolveByCgroupID maps a kernel cgroup ID (typically from a Tetragon or
	// own eBPF event) to a Subject.
	ResolveByCgroupID(context.Context, *CgroupIDRequest) (*SubjectResponse, error)
	// ResolveByPID maps a host PID to a Subject. Uses /proc + cgroup index.
	ResolveByPID(context.Context, *PIDRequest) (*SubjectResponse, error)
	// ResolveByPodIP maps a Pod IP (IPv4 or IPv6) to a Subject.
	ResolveByPodIP(context.Context, *PodIPRequest) (*SubjectResponse, error)
	// ResolveByPodUID maps a Pod UID (e.g. from an audit log entry) to a Subject.
	ResolveByPodUID(context.Context, *PodUIDRequest) (*SubjectResponse, error)
	// ResolveByContainerID maps a CRI container ID (e.g. "containerd://abc...")
	// to a Subject.
	ResolveByContainerID(context.Context, *ContainerIDRequest) (*SubjectResponse, error)
	// ResolveBySAUsername maps a Kubernetes auth username
	// (e.g. "system:serviceaccount:default:foo") to a Subject. Intelligent
	// parsing: system:serviceaccount:<ns>:<name>, system:node:<hostname>,
	// other system:* (returns SystemUser external), or non-system (ExternalUser).
	ResolveBySAUsername(context.Context, *SAUsernameRequest) (*SubjectResponse, error)
	// Watch streams SubjectChange events for the given filter. Server-streaming.
	// Planned for v1beta1 (operator hot-reload + cache prefetch).
	Watch(*WatchRequest, grpc.ServerStreamingServer[SubjectChange]) error
	mustEmbedUnimplementedResolverServer()
}

// UnimplementedResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedResolverServer struct{}

func (UnimplementedResolverServer) ResolveByCgroupID(context.Context, *CgroupIDRequest) (*SubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveByCgroupID not implemented")
}
func (UnimplementedResolverServer) ResolveByPID(context.Context, *PIDRequest) (*SubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveByPID not implemented")
}
func (UnimplementedResolverServer) ResolveByPodIP(context.Context, *PodIPRequest) (*SubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveByPodIP not implemented")
}
func (UnimplementedResolverServer) ResolveByPodUID(context.Context, *PodUIDRequest) (*SubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveByPodUID not implemented")
}
func (UnimplementedResolverServer) ResolveByContainerID(context.Context, *ContainerIDRequest) (*SubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveByContainerID not implemented")
}
func (UnimplementedResolverServer) ResolveBySAUsername(context.Context, *SAUsernameRequest) (*SubjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveBySAUsername not implemented")
}
func (UnimplementedResolverServer) Watch(*WatchRequest, grpc.ServerStreamingServer[SubjectChange]) error {
	return status.Error(codes.Unimplemented, "method Watch not implemented")
}
func (UnimplementedResolverServer) mustEmbedUnimplementedResolverServer() {}
func (UnimplementedResolverServer) testEmbeddedByValue()                  {}

// UnsafeResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResolverServer will
// result in compilation errors.
type UnsafeResolverServer interface {
	mustEmbedUnimplementedResolverServer()
}

func RegisterResolverServer(s grpc.ServiceRegistrar, srv ResolverServer) {
	// If the following call panics, it indicates UnimplementedResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Resolver_ServiceDesc, srv)
}

func _Resolver_ResolveByCgroupID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CgroupIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveByCgroupID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveByCgroupID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveByCgroupID(ctx, req.(*CgroupIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_ResolveByPID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveByPID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveByPID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveByPID(ctx, req.(*PIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_ResolveByPodIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveByPodIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveByPodIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveByPodIP(ctx, req.(*PodIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_ResolveByPodUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveByPodUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveByPodUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveByPodUID(ctx, req.(*PodUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_ResolveByContainerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveByContainerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveByContainerID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveByContainerID(ctx, req.(*ContainerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_ResolveBySAUsername_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAUsernameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResolverServer).ResolveBySAUsername(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resolver_ResolveBySAUsername_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResolverServer).ResolveBySAUsername(ctx, req.(*SAUsernameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resolver_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ResolverServer).Watch(m, &grpc.GenericServerStream[WatchRequest, SubjectChange]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Resolver_WatchServer = grpc.ServerStreamingServer[SubjectChange]

// Resolver_ServiceDesc is the grpc.ServiceDesc for Resolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ugallu.resolver.v1.Resolver",
	HandlerType: (*ResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveByCgroupID",
			Handler:    _Resolver_ResolveByCgroupID_Handler,
		},
		{
			MethodName: "ResolveByPID",
			Handler:    _Resolver_ResolveByPID_Handler,
		},
		{
			MethodName: "ResolveByPodIP",
			Handler:    _Resolver_ResolveByPodIP_Handler,
		},
		{
			MethodName: "ResolveByPodUID",
			Handler:    _Resolver_ResolveByPodUID_Handler,
		},
		{
			MethodName: "ResolveByContainerID",
			Handler:    _Resolver_ResolveByContainerID_Handler,
		},
		{
			MethodName: "ResolveBySAUsername",
			Handler:    _Resolver_ResolveBySAUsername_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _Resolver_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "resolver/v1/resolver.proto",
}
