// Copyright 2026 The ninsun-labs Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: resolver/v1/resolver.proto

// Package ugallu.resolver.v1 is the gRPC contract for ugallu-resolver
// (design 03 R6). The service is exposed on a Unix socket (per-node, fast
// path) and on a ClusterIP Service (cluster-wide). Clients are detection
// sources, reasoners, and responders that need to map low-level identifiers
// (cgroup ID, PID, IP, container ID, SA username) into a SubjectTier1
// snapshot suitable for embedding in a SecurityEvent.

package resolverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubjectChange_ChangeType int32

const (
	SubjectChange_UNKNOWN      SubjectChange_ChangeType = 0
	SubjectChange_ADDED        SubjectChange_ChangeType = 1
	SubjectChange_UPDATED      SubjectChange_ChangeType = 2
	SubjectChange_DELETED      SubjectChange_ChangeType = 3
	SubjectChange_TOMBSTONE_GC SubjectChange_ChangeType = 4
)

// Enum value maps for SubjectChange_ChangeType.
var (
	SubjectChange_ChangeType_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADDED",
		2: "UPDATED",
		3: "DELETED",
		4: "TOMBSTONE_GC",
	}
	SubjectChange_ChangeType_value = map[string]int32{
		"UNKNOWN":      0,
		"ADDED":        1,
		"UPDATED":      2,
		"DELETED":      3,
		"TOMBSTONE_GC": 4,
	}
)

func (x SubjectChange_ChangeType) Enum() *SubjectChange_ChangeType {
	p := new(SubjectChange_ChangeType)
	*p = x
	return p
}

func (x SubjectChange_ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubjectChange_ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_resolver_v1_resolver_proto_enumTypes[0].Descriptor()
}

func (SubjectChange_ChangeType) Type() protoreflect.EnumType {
	return &file_resolver_v1_resolver_proto_enumTypes[0]
}

func (x SubjectChange_ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubjectChange_ChangeType.Descriptor instead.
func (SubjectChange_ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{7, 0}
}

type CgroupIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CgroupId      uint64                 `protobuf:"varint,1,opt,name=cgroup_id,json=cgroupId,proto3" json:"cgroup_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CgroupIDRequest) Reset() {
	*x = CgroupIDRequest{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CgroupIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CgroupIDRequest) ProtoMessage() {}

func (x *CgroupIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CgroupIDRequest.ProtoReflect.Descriptor instead.
func (*CgroupIDRequest) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{0}
}

func (x *CgroupIDRequest) GetCgroupId() uint64 {
	if x != nil {
		return x.CgroupId
	}
	return 0
}

type PIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           int32                  `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PIDRequest) Reset() {
	*x = PIDRequest{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PIDRequest) ProtoMessage() {}

func (x *PIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PIDRequest.ProtoReflect.Descriptor instead.
func (*PIDRequest) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{1}
}

func (x *PIDRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

type PodIPRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ip is the Pod IP, IPv4 ("10.244.3.5") or IPv6 ("2001:db8::1").
	Ip            string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodIPRequest) Reset() {
	*x = PodIPRequest{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodIPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodIPRequest) ProtoMessage() {}

func (x *PodIPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodIPRequest.ProtoReflect.Descriptor instead.
func (*PodIPRequest) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{2}
}

func (x *PodIPRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type PodUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodUIDRequest) Reset() {
	*x = PodUIDRequest{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodUIDRequest) ProtoMessage() {}

func (x *PodUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodUIDRequest.ProtoReflect.Descriptor instead.
func (*PodUIDRequest) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{3}
}

func (x *PodUIDRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type ContainerIDRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id is the CRI runtime ID, e.g. "containerd://abc123...".
	ContainerId   string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerIDRequest) Reset() {
	*x = ContainerIDRequest{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerIDRequest) ProtoMessage() {}

func (x *ContainerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerIDRequest.ProtoReflect.Descriptor instead.
func (*ContainerIDRequest) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerIDRequest) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

type SAUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SAUsernameRequest) Reset() {
	*x = SAUsernameRequest{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SAUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SAUsernameRequest) ProtoMessage() {}

func (x *SAUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SAUsernameRequest.ProtoReflect.Descriptor instead.
func (*SAUsernameRequest) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{5}
}

func (x *SAUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// kind filters by SubjectKind (empty for any).
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// namespace filter (empty for any).
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{6}
}

func (x *WatchRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *WatchRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type SubjectChange struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          SubjectChange_ChangeType `protobuf:"varint,1,opt,name=type,proto3,enum=ugallu.resolver.v1.SubjectChange_ChangeType" json:"type,omitempty"`
	Subject       *SubjectResponse         `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectChange) Reset() {
	*x = SubjectChange{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectChange) ProtoMessage() {}

func (x *SubjectChange) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectChange.ProtoReflect.Descriptor instead.
func (*SubjectChange) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{7}
}

func (x *SubjectChange) GetType() SubjectChange_ChangeType {
	if x != nil {
		return x.Type
	}
	return SubjectChange_UNKNOWN
}

func (x *SubjectChange) GetSubject() *SubjectResponse {
	if x != nil {
		return x.Subject
	}
	return nil
}

// SubjectResponse carries the resolver lookup result. The common identity
// fields are always populated when the subject is known; the full
// SubjectTier1 (including the per-kind discriminator) is encoded as
// JSON in tier1_json so clients can deserialize via encoding/json into
// the SDK Go type without mirroring the entire discriminator schema in
// proto. A future v2 contract will replace tier1_json with strong-typed
// oneof messages mirroring the discriminator.
type SubjectResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	ApiVersion      string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Uid             string                 `protobuf:"bytes,5,opt,name=uid,proto3" json:"uid,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,6,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Labels          map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// tier1_json is the JSON-encoded v1alpha1.SubjectTier1.
	Tier1Json []byte `protobuf:"bytes,10,opt,name=tier1_json,json=tier1Json,proto3" json:"tier1_json,omitempty"`
	// Failure markers (resolver fallback path, design 03).
	Partial    bool `protobuf:"varint,20,opt,name=partial,proto3" json:"partial,omitempty"`
	Tombstone  bool `protobuf:"varint,21,opt,name=tombstone,proto3" json:"tombstone,omitempty"`
	Unresolved bool `protobuf:"varint,22,opt,name=unresolved,proto3" json:"unresolved,omitempty"`
	// diagnostic is free-form (not a contract; for human/log inspection).
	Diagnostic    string `protobuf:"bytes,30,opt,name=diagnostic,proto3" json:"diagnostic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubjectResponse) Reset() {
	*x = SubjectResponse{}
	mi := &file_resolver_v1_resolver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubjectResponse) ProtoMessage() {}

func (x *SubjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_resolver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubjectResponse.ProtoReflect.Descriptor instead.
func (*SubjectResponse) Descriptor() ([]byte, []int) {
	return file_resolver_v1_resolver_proto_rawDescGZIP(), []int{8}
}

func (x *SubjectResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SubjectResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *SubjectResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SubjectResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SubjectResponse) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *SubjectResponse) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *SubjectResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SubjectResponse) GetTier1Json() []byte {
	if x != nil {
		return x.Tier1Json
	}
	return nil
}

func (x *SubjectResponse) GetPartial() bool {
	if x != nil {
		return x.Partial
	}
	return false
}

func (x *SubjectResponse) GetTombstone() bool {
	if x != nil {
		return x.Tombstone
	}
	return false
}

func (x *SubjectResponse) GetUnresolved() bool {
	if x != nil {
		return x.Unresolved
	}
	return false
}

func (x *SubjectResponse) GetDiagnostic() string {
	if x != nil {
		return x.Diagnostic
	}
	return ""
}

var File_resolver_v1_resolver_proto protoreflect.FileDescriptor

const file_resolver_v1_resolver_proto_rawDesc = "" +
	"\n" +
	"\x1aresolver/v1/resolver.proto\x12\x12ugallu.resolver.v1\".\n" +
	"\x0fCgroupIDRequest\x12\x1b\n" +
	"\tcgroup_id\x18\x01 \x01(\x04R\bcgroupId\"\x1e\n" +
	"\n" +
	"PIDRequest\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\x05R\x03pid\"\x1e\n" +
	"\fPodIPRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"!\n" +
	"\rPodUIDRequest\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"7\n" +
	"\x12ContainerIDRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\"/\n" +
	"\x11SAUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"@\n" +
	"\fWatchRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xe2\x01\n" +
	"\rSubjectChange\x12@\n" +
	"\x04type\x18\x01 \x01(\x0e2,.ugallu.resolver.v1.SubjectChange.ChangeTypeR\x04type\x12=\n" +
	"\asubject\x18\x02 \x01(\v2#.ugallu.resolver.v1.SubjectResponseR\asubject\"P\n" +
	"\n" +
	"ChangeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05ADDED\x10\x01\x12\v\n" +
	"\aUPDATED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03\x12\x10\n" +
	"\fTOMBSTONE_GC\x10\x04\"\xd0\x03\n" +
	"\x0fSubjectResponse\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\tR\x03uid\x12)\n" +
	"\x10resource_version\x18\x06 \x01(\tR\x0fresourceVersion\x12G\n" +
	"\x06labels\x18\a \x03(\v2/.ugallu.resolver.v1.SubjectResponse.LabelsEntryR\x06labels\x12\x1d\n" +
	"\n" +
	"tier1_json\x18\n" +
	" \x01(\fR\ttier1Json\x12\x18\n" +
	"\apartial\x18\x14 \x01(\bR\apartial\x12\x1c\n" +
	"\ttombstone\x18\x15 \x01(\bR\ttombstone\x12\x1e\n" +
	"\n" +
	"unresolved\x18\x16 \x01(\bR\n" +
	"unresolved\x12\x1e\n" +
	"\n" +
	"diagnostic\x18\x1e \x01(\tR\n" +
	"diagnostic\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8a\x05\n" +
	"\bResolver\x12]\n" +
	"\x11ResolveByCgroupID\x12#.ugallu.resolver.v1.CgroupIDRequest\x1a#.ugallu.resolver.v1.SubjectResponse\x12S\n" +
	"\fResolveByPID\x12\x1e.ugallu.resolver.v1.PIDRequest\x1a#.ugallu.resolver.v1.SubjectResponse\x12W\n" +
	"\x0eResolveByPodIP\x12 .ugallu.resolver.v1.PodIPRequest\x1a#.ugallu.resolver.v1.SubjectResponse\x12Y\n" +
	"\x0fResolveByPodUID\x12!.ugallu.resolver.v1.PodUIDRequest\x1a#.ugallu.resolver.v1.SubjectResponse\x12c\n" +
	"\x14ResolveByContainerID\x12&.ugallu.resolver.v1.ContainerIDRequest\x1a#.ugallu.resolver.v1.SubjectResponse\x12a\n" +
	"\x13ResolveBySAUsername\x12%.ugallu.resolver.v1.SAUsernameRequest\x1a#.ugallu.resolver.v1.SubjectResponse\x12N\n" +
	"\x05Watch\x12 .ugallu.resolver.v1.WatchRequest\x1a!.ugallu.resolver.v1.SubjectChange0\x01BDZBgithub.com/ninsun-labs/ugallu/sdk/pkg/resolver/clientv1;resolverv1b\x06proto3"

var (
	file_resolver_v1_resolver_proto_rawDescOnce sync.Once
	file_resolver_v1_resolver_proto_rawDescData []byte
)

func file_resolver_v1_resolver_proto_rawDescGZIP() []byte {
	file_resolver_v1_resolver_proto_rawDescOnce.Do(func() {
		file_resolver_v1_resolver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_resolver_v1_resolver_proto_rawDesc), len(file_resolver_v1_resolver_proto_rawDesc)))
	})
	return file_resolver_v1_resolver_proto_rawDescData
}

var file_resolver_v1_resolver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resolver_v1_resolver_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_resolver_v1_resolver_proto_goTypes = []any{
	(SubjectChange_ChangeType)(0), // 0: ugallu.resolver.v1.SubjectChange.ChangeType
	(*CgroupIDRequest)(nil),       // 1: ugallu.resolver.v1.CgroupIDRequest
	(*PIDRequest)(nil),            // 2: ugallu.resolver.v1.PIDRequest
	(*PodIPRequest)(nil),          // 3: ugallu.resolver.v1.PodIPRequest
	(*PodUIDRequest)(nil),         // 4: ugallu.resolver.v1.PodUIDRequest
	(*ContainerIDRequest)(nil),    // 5: ugallu.resolver.v1.ContainerIDRequest
	(*SAUsernameRequest)(nil),     // 6: ugallu.resolver.v1.SAUsernameRequest
	(*WatchRequest)(nil),          // 7: ugallu.resolver.v1.WatchRequest
	(*SubjectChange)(nil),         // 8: ugallu.resolver.v1.SubjectChange
	(*SubjectResponse)(nil),       // 9: ugallu.resolver.v1.SubjectResponse
	nil,                           // 10: ugallu.resolver.v1.SubjectResponse.LabelsEntry
}
var file_resolver_v1_resolver_proto_depIdxs = []int32{
	0,  // 0: ugallu.resolver.v1.SubjectChange.type:type_name -> ugallu.resolver.v1.SubjectChange.ChangeType
	9,  // 1: ugallu.resolver.v1.SubjectChange.subject:type_name -> ugallu.resolver.v1.SubjectResponse
	10, // 2: ugallu.resolver.v1.SubjectResponse.labels:type_name -> ugallu.resolver.v1.SubjectResponse.LabelsEntry
	1,  // 3: ugallu.resolver.v1.Resolver.ResolveByCgroupID:input_type -> ugallu.resolver.v1.CgroupIDRequest
	2,  // 4: ugallu.resolver.v1.Resolver.ResolveByPID:input_type -> ugallu.resolver.v1.PIDRequest
	3,  // 5: ugallu.resolver.v1.Resolver.ResolveByPodIP:input_type -> ugallu.resolver.v1.PodIPRequest
	4,  // 6: ugallu.resolver.v1.Resolver.ResolveByPodUID:input_type -> ugallu.resolver.v1.PodUIDRequest
	5,  // 7: ugallu.resolver.v1.Resolver.ResolveByContainerID:input_type -> ugallu.resolver.v1.ContainerIDRequest
	6,  // 8: ugallu.resolver.v1.Resolver.ResolveBySAUsername:input_type -> ugallu.resolver.v1.SAUsernameRequest
	7,  // 9: ugallu.resolver.v1.Resolver.Watch:input_type -> ugallu.resolver.v1.WatchRequest
	9,  // 10: ugallu.resolver.v1.Resolver.ResolveByCgroupID:output_type -> ugallu.resolver.v1.SubjectResponse
	9,  // 11: ugallu.resolver.v1.Resolver.ResolveByPID:output_type -> ugallu.resolver.v1.SubjectResponse
	9,  // 12: ugallu.resolver.v1.Resolver.ResolveByPodIP:output_type -> ugallu.resolver.v1.SubjectResponse
	9,  // 13: ugallu.resolver.v1.Resolver.ResolveByPodUID:output_type -> ugallu.resolver.v1.SubjectResponse
	9,  // 14: ugallu.resolver.v1.Resolver.ResolveByContainerID:output_type -> ugallu.resolver.v1.SubjectResponse
	9,  // 15: ugallu.resolver.v1.Resolver.ResolveBySAUsername:output_type -> ugallu.resolver.v1.SubjectResponse
	8,  // 16: ugallu.resolver.v1.Resolver.Watch:output_type -> ugallu.resolver.v1.SubjectChange
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_resolver_v1_resolver_proto_init() }
func file_resolver_v1_resolver_proto_init() {
	if File_resolver_v1_resolver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resolver_v1_resolver_proto_rawDesc), len(file_resolver_v1_resolver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resolver_v1_resolver_proto_goTypes,
		DependencyIndexes: file_resolver_v1_resolver_proto_depIdxs,
		EnumInfos:         file_resolver_v1_resolver_proto_enumTypes,
		MessageInfos:      file_resolver_v1_resolver_proto_msgTypes,
	}.Build()
	File_resolver_v1_resolver_proto = out.File
	file_resolver_v1_resolver_proto_goTypes = nil
	file_resolver_v1_resolver_proto_depIdxs = nil
}
