// Copyright 2026 The ninsun-labs Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: auditstream/v1/audit_stream.proto

// Package ugallu.auditstream.v1 is the gRPC contract for the
// audit-detection event bus (design 21 §S2). audit-detection
// re-emits every consumed apiserver audit event on a streaming
// channel so other operators (tenant-escape Wave 3, future
// reasoners) can subscribe without independently tailing the
// apiserver audit log.
//
// The bus runs only when AuditDetectionConfig.spec.eventBus.enabled
// is true.

package auditstreamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SubscribeRequest is the client-side declaration sent once at the
// start of the stream.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ConsumerName is the human-readable consumer id (must match an
	// entry in AuditDetectionConfig.spec.consumers — events are
	// filtered + rate-limited per the matching consumer entry).
	ConsumerName  string `protobuf:"bytes,1,opt,name=consumer_name,json=consumerName,proto3" json:"consumer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_auditstream_v1_audit_stream_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetConsumerName() string {
	if x != nil {
		return x.ConsumerName
	}
	return ""
}

// AuditEvent is one observed apiserver audit event, normalised
// across the audit log shapes (file backend / webhook backend).
// Fields are nullable when the source can't populate them.
type AuditEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// AuditID is the apiserver-issued unique id (RFC 4122 UUID).
	AuditId string `protobuf:"bytes,2,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	// Stage is the audit stage (RequestReceived, ResponseStarted,
	// ResponseComplete, Panic). audit-detection forwards the
	// ResponseComplete stage (the canonical "this happened" event).
	Stage string `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	// Verb is the HTTP-level verb (get, list, create, update, patch,
	// delete, watch, deletecollection, ...).
	Verb string `protobuf:"bytes,4,opt,name=verb,proto3" json:"verb,omitempty"`
	// User is the authenticated user that issued the request.
	User *AuditUser `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	// ImpersonatedUser is the --as user when the request was
	// impersonated. Non-nil when impersonation was used.
	ImpersonatedUser *AuditUser `protobuf:"bytes,6,opt,name=impersonated_user,json=impersonatedUser,proto3" json:"impersonated_user,omitempty"`
	// ObjectRef identifies the resource the request targets.
	ObjectRef *ObjectReference `protobuf:"bytes,7,opt,name=object_ref,json=objectRef,proto3" json:"object_ref,omitempty"`
	// RequestObject is the JSON-encoded request body. Empty for
	// get/list/watch/delete (the apiserver audit policy controls
	// when this is populated).
	RequestObject []byte `protobuf:"bytes,8,opt,name=request_object,json=requestObject,proto3" json:"request_object,omitempty"`
	// ResponseObject is the JSON-encoded response body. Same caveats
	// as RequestObject.
	ResponseObject []byte `protobuf:"bytes,9,opt,name=response_object,json=responseObject,proto3" json:"response_object,omitempty"`
	// ResponseStatus.code mirrors the HTTP status code returned to
	// the client.
	ResponseStatusCode uint32 `protobuf:"varint,10,opt,name=response_status_code,json=responseStatusCode,proto3" json:"response_status_code,omitempty"`
	// SourceIPs is the chain of forwarder IPs (X-Forwarded-For style).
	SourceIps []string `protobuf:"bytes,11,rep,name=source_ips,json=sourceIps,proto3" json:"source_ips,omitempty"`
	// UserAgent is the client UA string.
	UserAgent     string `protobuf:"bytes,12,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_auditstream_v1_audit_stream_proto_rawDescGZIP(), []int{1}
}

func (x *AuditEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AuditEvent) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *AuditEvent) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *AuditEvent) GetVerb() string {
	if x != nil {
		return x.Verb
	}
	return ""
}

func (x *AuditEvent) GetUser() *AuditUser {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *AuditEvent) GetImpersonatedUser() *AuditUser {
	if x != nil {
		return x.ImpersonatedUser
	}
	return nil
}

func (x *AuditEvent) GetObjectRef() *ObjectReference {
	if x != nil {
		return x.ObjectRef
	}
	return nil
}

func (x *AuditEvent) GetRequestObject() []byte {
	if x != nil {
		return x.RequestObject
	}
	return nil
}

func (x *AuditEvent) GetResponseObject() []byte {
	if x != nil {
		return x.ResponseObject
	}
	return nil
}

func (x *AuditEvent) GetResponseStatusCode() uint32 {
	if x != nil {
		return x.ResponseStatusCode
	}
	return 0
}

func (x *AuditEvent) GetSourceIps() []string {
	if x != nil {
		return x.SourceIps
	}
	return nil
}

func (x *AuditEvent) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

// AuditUser identifies the authenticated principal.
type AuditUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Groups        []string               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditUser) Reset() {
	*x = AuditUser{}
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditUser) ProtoMessage() {}

func (x *AuditUser) ProtoReflect() protoreflect.Message {
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditUser.ProtoReflect.Descriptor instead.
func (*AuditUser) Descriptor() ([]byte, []int) {
	return file_auditstream_v1_audit_stream_proto_rawDescGZIP(), []int{2}
}

func (x *AuditUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuditUser) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

// ObjectReference identifies an apiserver resource.
type ObjectReference struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiGroup      string                 `protobuf:"bytes,1,opt,name=api_group,json=apiGroup,proto3" json:"api_group,omitempty"`
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Resource      string                 `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	Subresource   string                 `protobuf:"bytes,4,opt,name=subresource,proto3" json:"subresource,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Uid           string                 `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObjectReference) Reset() {
	*x = ObjectReference{}
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectReference) ProtoMessage() {}

func (x *ObjectReference) ProtoReflect() protoreflect.Message {
	mi := &file_auditstream_v1_audit_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectReference.ProtoReflect.Descriptor instead.
func (*ObjectReference) Descriptor() ([]byte, []int) {
	return file_auditstream_v1_audit_stream_proto_rawDescGZIP(), []int{3}
}

func (x *ObjectReference) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *ObjectReference) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *ObjectReference) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *ObjectReference) GetSubresource() string {
	if x != nil {
		return x.Subresource
	}
	return ""
}

func (x *ObjectReference) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ObjectReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectReference) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

var File_auditstream_v1_audit_stream_proto protoreflect.FileDescriptor

const file_auditstream_v1_audit_stream_proto_rawDesc = "" +
	"\n" +
	"!auditstream/v1/audit_stream.proto\x12\x15ugallu.auditstream.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"7\n" +
	"\x10SubscribeRequest\x12#\n" +
	"\rconsumer_name\x18\x01 \x01(\tR\fconsumerName\"\x97\x04\n" +
	"\n" +
	"AuditEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\baudit_id\x18\x02 \x01(\tR\aauditId\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x12\n" +
	"\x04verb\x18\x04 \x01(\tR\x04verb\x124\n" +
	"\x04user\x18\x05 \x01(\v2 .ugallu.auditstream.v1.AuditUserR\x04user\x12M\n" +
	"\x11impersonated_user\x18\x06 \x01(\v2 .ugallu.auditstream.v1.AuditUserR\x10impersonatedUser\x12E\n" +
	"\n" +
	"object_ref\x18\a \x01(\v2&.ugallu.auditstream.v1.ObjectReferenceR\tobjectRef\x12%\n" +
	"\x0erequest_object\x18\b \x01(\fR\rrequestObject\x12'\n" +
	"\x0fresponse_object\x18\t \x01(\fR\x0eresponseObject\x120\n" +
	"\x14response_status_code\x18\n" +
	" \x01(\rR\x12responseStatusCode\x12\x1d\n" +
	"\n" +
	"source_ips\x18\v \x03(\tR\tsourceIps\x12\x1d\n" +
	"\n" +
	"user_agent\x18\f \x01(\tR\tuserAgent\"?\n" +
	"\tAuditUser\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x16\n" +
	"\x06groups\x18\x02 \x03(\tR\x06groups\"\xd1\x01\n" +
	"\x0fObjectReference\x12\x1b\n" +
	"\tapi_group\x18\x01 \x01(\tR\bapiGroup\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x1a\n" +
	"\bresource\x18\x03 \x01(\tR\bresource\x12 \n" +
	"\vsubresource\x18\x04 \x01(\tR\vsubresource\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\a \x01(\tR\x03uid2h\n" +
	"\vAuditStream\x12Y\n" +
	"\tSubscribe\x12'.ugallu.auditstream.v1.SubscribeRequest\x1a!.ugallu.auditstream.v1.AuditEvent0\x01BJZHgithub.com/ninsun-labs/ugallu/sdk/pkg/auditstream/clientv1;auditstreamv1b\x06proto3"

var (
	file_auditstream_v1_audit_stream_proto_rawDescOnce sync.Once
	file_auditstream_v1_audit_stream_proto_rawDescData []byte
)

func file_auditstream_v1_audit_stream_proto_rawDescGZIP() []byte {
	file_auditstream_v1_audit_stream_proto_rawDescOnce.Do(func() {
		file_auditstream_v1_audit_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auditstream_v1_audit_stream_proto_rawDesc), len(file_auditstream_v1_audit_stream_proto_rawDesc)))
	})
	return file_auditstream_v1_audit_stream_proto_rawDescData
}

var file_auditstream_v1_audit_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auditstream_v1_audit_stream_proto_goTypes = []any{
	(*SubscribeRequest)(nil),      // 0: ugallu.auditstream.v1.SubscribeRequest
	(*AuditEvent)(nil),            // 1: ugallu.auditstream.v1.AuditEvent
	(*AuditUser)(nil),             // 2: ugallu.auditstream.v1.AuditUser
	(*ObjectReference)(nil),       // 3: ugallu.auditstream.v1.ObjectReference
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_auditstream_v1_audit_stream_proto_depIdxs = []int32{
	4, // 0: ugallu.auditstream.v1.AuditEvent.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: ugallu.auditstream.v1.AuditEvent.user:type_name -> ugallu.auditstream.v1.AuditUser
	2, // 2: ugallu.auditstream.v1.AuditEvent.impersonated_user:type_name -> ugallu.auditstream.v1.AuditUser
	3, // 3: ugallu.auditstream.v1.AuditEvent.object_ref:type_name -> ugallu.auditstream.v1.ObjectReference
	0, // 4: ugallu.auditstream.v1.AuditStream.Subscribe:input_type -> ugallu.auditstream.v1.SubscribeRequest
	1, // 5: ugallu.auditstream.v1.AuditStream.Subscribe:output_type -> ugallu.auditstream.v1.AuditEvent
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_auditstream_v1_audit_stream_proto_init() }
func file_auditstream_v1_audit_stream_proto_init() {
	if File_auditstream_v1_audit_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auditstream_v1_audit_stream_proto_rawDesc), len(file_auditstream_v1_audit_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auditstream_v1_audit_stream_proto_goTypes,
		DependencyIndexes: file_auditstream_v1_audit_stream_proto_depIdxs,
		MessageInfos:      file_auditstream_v1_audit_stream_proto_msgTypes,
	}.Build()
	File_auditstream_v1_audit_stream_proto = out.File
	file_auditstream_v1_audit_stream_proto_goTypes = nil
	file_auditstream_v1_audit_stream_proto_depIdxs = nil
}
