// Copyright 2026 The ninsun-labs Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: auditstream/v1/audit_stream.proto

// Package ugallu.auditstream.v1 is the gRPC contract for the
// audit-detection event bus (design 21 §S2). audit-detection
// re-emits every consumed apiserver audit event on a streaming
// channel so other operators (tenant-escape Wave 3, future
// reasoners) can subscribe without independently tailing the
// apiserver audit log.
//
// The bus runs only when AuditDetectionConfig.spec.eventBus.enabled
// is true.

package auditstreamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditStream_Subscribe_FullMethodName = "/ugallu.auditstream.v1.AuditStream/Subscribe"
)

// AuditStreamClient is the client API for AuditStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuditStream is the server-streaming RPC the audit-detection
// operator exposes.
type AuditStreamClient interface {
	// Subscribe streams every audit event matching the consumer
	// filter until the client disconnects or the server shuts down.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error)
}

type auditStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditStreamClient(cc grpc.ClientConnInterface) AuditStreamClient {
	return &auditStreamClient{cc}
}

func (c *auditStreamClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AuditEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AuditStream_ServiceDesc.Streams[0], AuditStream_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, AuditEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditStream_SubscribeClient = grpc.ServerStreamingClient[AuditEvent]

// AuditStreamServer is the server API for AuditStream service.
// All implementations must embed UnimplementedAuditStreamServer
// for forward compatibility.
//
// AuditStream is the server-streaming RPC the audit-detection
// operator exposes.
type AuditStreamServer interface {
	// Subscribe streams every audit event matching the consumer
	// filter until the client disconnects or the server shuts down.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[AuditEvent]) error
	mustEmbedUnimplementedAuditStreamServer()
}

// UnimplementedAuditStreamServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditStreamServer struct{}

func (UnimplementedAuditStreamServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[AuditEvent]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAuditStreamServer) mustEmbedUnimplementedAuditStreamServer() {}
func (UnimplementedAuditStreamServer) testEmbeddedByValue()                     {}

// UnsafeAuditStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditStreamServer will
// result in compilation errors.
type UnsafeAuditStreamServer interface {
	mustEmbedUnimplementedAuditStreamServer()
}

func RegisterAuditStreamServer(s grpc.ServiceRegistrar, srv AuditStreamServer) {
	// If the following call panics, it indicates UnimplementedAuditStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditStream_ServiceDesc, srv)
}

func _AuditStream_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AuditStreamServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, AuditEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AuditStream_SubscribeServer = grpc.ServerStreamingServer[AuditEvent]

// AuditStream_ServiceDesc is the grpc.ServiceDesc for AuditStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ugallu.auditstream.v1.AuditStream",
	HandlerType: (*AuditStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _AuditStream_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "auditstream/v1/audit_stream.proto",
}
