apiVersion: v1
kind: ServiceAccount
metadata:
  name: ugallu-webhook-auditor
  namespace: {{ include "webhookauditor.namespace" . }}
  labels:
    {{- include "webhookauditor.labels" . | nindent 4 }}
