// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package serverv1

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCgroupTracker returns the embedded CollectionSpec for cgroupTracker.
func loadCgroupTracker() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CgroupTrackerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cgroupTracker: %w", err)
	}

	return spec, err
}

// loadCgroupTrackerObjects loads cgroupTracker and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cgroupTrackerObjects
//	*cgroupTrackerPrograms
//	*cgroupTrackerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCgroupTrackerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCgroupTracker()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cgroupTrackerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupTrackerSpecs struct {
	cgroupTrackerProgramSpecs
	cgroupTrackerMapSpecs
	cgroupTrackerVariableSpecs
}

// cgroupTrackerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupTrackerProgramSpecs struct {
	HandleMkdir *ebpf.ProgramSpec `ebpf:"handle_mkdir"`
	HandleRmdir *ebpf.ProgramSpec `ebpf:"handle_rmdir"`
}

// cgroupTrackerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupTrackerMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// cgroupTrackerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cgroupTrackerVariableSpecs struct {
}

// cgroupTrackerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCgroupTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupTrackerObjects struct {
	cgroupTrackerPrograms
	cgroupTrackerMaps
	cgroupTrackerVariables
}

func (o *cgroupTrackerObjects) Close() error {
	return _CgroupTrackerClose(
		&o.cgroupTrackerPrograms,
		&o.cgroupTrackerMaps,
	)
}

// cgroupTrackerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCgroupTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupTrackerMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *cgroupTrackerMaps) Close() error {
	return _CgroupTrackerClose(
		m.Events,
	)
}

// cgroupTrackerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCgroupTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupTrackerVariables struct {
}

// cgroupTrackerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCgroupTrackerObjects or ebpf.CollectionSpec.LoadAndAssign.
type cgroupTrackerPrograms struct {
	HandleMkdir *ebpf.Program `ebpf:"handle_mkdir"`
	HandleRmdir *ebpf.Program `ebpf:"handle_rmdir"`
}

func (p *cgroupTrackerPrograms) Close() error {
	return _CgroupTrackerClose(
		p.HandleMkdir,
		p.HandleRmdir,
	)
}

func _CgroupTrackerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cgrouptracker_x86_bpfel.o
var _CgroupTrackerBytes []byte
