global:
  namespaces:
    system: ugallu-system

placeholder: true

image:
  repository: ghcr.io/ninsun-labs/ugallu/attestor
  tag: "v0.1.0-alpha.2"
  pullPolicy: IfNotPresent

command: ["/bin/sleep", "infinity"]
args: []

# Replicas for HA. The leader-elect Lease ensures only one is active.
replicas: 2

resources:
  requests:
    cpu: "5m"
    memory: "64Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

metricsPort: 9090

nodeSelector: {}
tolerations: []
affinity: {}
