apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugallu-tenant-escape
  namespace: {{ include "tenantescape.namespace" . }}
  labels:
    {{- include "tenantescape.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "tenantescape.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tenantescape.labels" . | nindent 8 }}
      annotations:
        ugallu.io/scaffold: {{ .Values.placeholder | quote }}
    spec:
      serviceAccountName: ugallu-tenant-escape
      priorityClassName: system-cluster-critical
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tenant-escape
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ toJson .Values.command }}
          args: {{ toJson .Values.args }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort }}
              protocol: TCP
          env:
            - name: AUDIT_BUS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auditBus.tokenSecret.name }}
                  key: {{ .Values.auditBus.tokenSecret.key }}
                  optional: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
